src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="attention ,la date d'arrivée doit étre au bon format !")
     * @assert\GreaterThan("today",message="la date d'arrivée doit étre ultérieure à la date d'aujourd'hui !",groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="attention ,la date de départ doit étre au bon format !")
     * @assert\GreaterThan(propertyPath="startDate",message="la date de départ doit étre éloignée à la date d'arrive !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    public function isBookablesDates(){
// 1)il faut connaitre les dates qui sont impossibles pourl'annonce
     $notAvailableDays=$this->ad->getNotAvailableDays();

// 2) il faut comparer les dates choisies avec les dates impossibles
    $bookingDays=$this->getDays();
    $formatDay=function($day){ return $day->format('y-m-d');};
    //Tableau des chaines de caractéres de me journées
    $days=array_map($formatDay,$bookingDays);
    $notAvailable=array_map($formatDay,$notAvailableDays);

    foreach($days as $day){
        if(array_search($day ,$notAvailable) !==false) return false;
    }
return true;
    }
    /**
     * Permet de récupérer un tableau des journées qui correspondent à ma réservation 
     * @return array Un tableau d'objets DateTime représentant les jours de la réservation
     * 
     */

    public function getDays(){


        $resultat =range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60 
        );
        $days=array_map(function($dayTimestamp){
            return new \DateTime(date('y-m-d',$dayTimestamp));
        },$resultat);
        return $days;
    }


/**
 * Callback appelé à chaque fois qu'on créé une réservation
 * @ORM\PrePersist
 * @ORM\PreUpdate
 *
 * @return void
 */
    public function prePersist(){
        if(empty($this->createdAt)){
            $this->createdAt=new \DateTime();
        }
        if(empty($this->amount)){
            $this->amount = $this->ad->getPrice()*$this->getDuration();
        }



    }
    public function getDuration(){
        $diff=$this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur s'est déja inscit avec cette adresse email,merci de la modifier"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une Url valide pour votre avatar !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,minMessage="votre introduction doit faire au moins 10 caractéres")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100,minMessage="Votre description doit faire au moins 100 caractéres")
     */
    private $descritption;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;
    /**
     * 
     * @Assert\EqualTo(propertyPath="hash",message="Vous n'aves pas correctement confirmé votre mot de pass !")
     */

    public $passwordConfirm;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

public function getFullName(){
    return "{$this->firstName} {$this->LastName}";
}


    /**
 * Permet d'initialiser le slug !
 *
 * @ORM\PrePersist
 * @ORM\PreUpdate
 * @return void
 */
public function initializeSlug(){
    if(empty($this->slug)){
        $slugify=new Slugify();
        $this->slug=$slugify->slugify($this->firstName.' '.$this->LastName);
    }
}

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescritption(): ?string
    {
        return $this->descritption;
    }

    public function setDescritption(string $descritption): self
    {
        $this->descritption = $descritption;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }
    public function getRoles(){
       
       
        $roles=$this->userRoles->map(function($roles){
            return $roles->getTitle();
        })->toArray();
        $roles[]='ROLE_USER';
        return $roles;

    }
    public function getPassword(){
        return $this->hash;
    }
    public function getSalt(){}
    public function getUsername(){
        return $this->email;
    } 
    public function eraseCredentials(){
        
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class BookingType extends ApplicationType

{
private $transformer;
public function __construct(FrenchToDateTimeTransformer $transformer){
    $this->transformer=$transformer;  
}





    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate',TextType::class,$this->getConfiguration("Date d'arrive","La date à laquelle vous comptez arriver"))
            ->add('endDate',TextType::class,$this->getConfiguration("Date de départ","La date à laquelle vous quittez les lieux"))
         ->add('comment',TextareaType::class,$this->getConfiguration(false,"Si vous aves un commentaire,n'hésitez pas à en faire part !",["required"=> false ]))
        ;
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups'=>[
                'Default',
                'front'
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     *
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {$booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $booking->setBooker($user)
                ->setAd($ad);
            //Si les dates ne sont pas disponibles,message d'erreur
            if (!$booking->isBookablesDates()) {
                $this->addFlash(
                    'warning',
                    "Les dates que vous avez choisi ne peuvent étre réservées :elles sont déja prises"
                );

            } else {
                //Sinon enregistrement et redirection
                $manager->persist($booking);
                $manager->flush();
                return $this->redirectToRoute('booking_show', ['id' => $booking->getId(),
                    'withAlert' => true]);

            }

        }
        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView(),
        ]);
    }
    /**
     * Permet d'afficher la page d'une réservation
     *
     * @Route("/booking/{id}",name="booking_show")
     *
     * @param Booking $booking
     * @param Request $resquest
     * @param ObjectManager $manager
     * @return Response
     */
    public function show(Booking $booking,Request $request,ObjectManager $manager)
    {
        $comment = new Comment();
        $form=$this->createForm(CommentType::class,$comment,[
            
        ]);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $comment->setAd($booking->getAd())
            ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',"Votre commentaire a bien été pris en compte !"
            );

        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form'  =>$form->createView()
        ]);
    }

}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce :
	{{ad.title}}
{% endblock %}
{% block stylesheets %}
	<!-- <link rel="stylesheet" href="/css/bootstrap-datepicker.min.css"/> -->
 {{ encore_entry_link_tags('app') }}

{% endblock %}

{% block body %}
	<div class="container">
		<h1>Réserver pour l'annonce :<em>{{ ad.title}}</em></h1>
		<p>Vous etes sur le point de réserver le bien de
			<strnog>{{ad.author.fullName}}</strong>
			dites nous tout,on s'occupe du reste !</p>
		{{ form_start(form) }}
		<div class="alert alert-light">
			<h2 class="h4">Commencez par nous dire quelles sont les date qui vous intéressent</h2>
			<div class="row">
				<div class="col">
					{{form_row(form.startDate)}}

				</div>
				<div class="col">
					{{form_row(form.endDate)}}
				</div>
			</div>

		<h4 class="mt-2">Montant du séjour :
			<span id="amount">....</span>&euro;
		</h4>
		<span id="days">0</span>
		nuit(s) à
		{{ ad.price | number_format(2,',',' ') }} &euro;
		par nuit
		<h4 class="mt-3">Vous aves un commentaire ?</h4>
		{{ form_row(form.comment)}}
		</div>
		<h2>Vous aves terminé !</h2>
		<p>Vacances de réve ? Hébergement pour le boulot ? Peu import, on est avec vous !</P>
		<button type="submit" class="btn btn-success">Je réserve !</button>
		{{form_end(form)}}
	</div>
{% endblock %}
{% block javascripts %}
	<!-- <script src="/js/bootstrap-datepicker.min.js"></script> -->

			{{ parent() }}
			{{ encore_entry_script_tags('datejs') }}
			
			




	<script>
		$(document).ready(function () {
$('#booking_startDate,#booking_endDate').datepicker({
		format: 'dd/mm/yyyy',
		datesDisabled: [
				{% for day in ad.notAvailableDays %}
			     
				 "{{ day.format('d/m/Y') }}",
					
				{% endfor %}
						
						],
						startDate: new Date()
});
$('#booking_startDate,#booking_endDate').on('change',calculateAmount); 
});

function calculateAmount(){
	//On chope les dates
	const endDate =new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
	//18/09/2020
	//(\d+)(\d+)\/(/d{4})
	// 2020/09/18 
	const startDate=new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/,'$3-$2-$1'));
	if(startDate && endDate && startDate < endDate){
		const DAY_TIME=24*60*60*1000;
		const interval =endDate.getTime() - startDate.getTime();
		const days =interval / DAY_TIME;
		const amount =days * {{ad.price}};
		$('#days').text(days);
		$('#amount').text(amount.toLocaleString('fr-FR'));
		
					}

}
	</script>

{% endblock %}

templates/booking/show.html.twig
{% extends "base.html.twig" %}
{% block title %}Réservation n°{{booking.id}}
{% endblock %}
{% block body %}
	{% set ad = booking.ad %}
	{% set author = ad.author %}

	<div class="container">
		<h1 class="my-5">Votre réservation (n°{{booking.id}})</h1>
		{% if app.request.query.get('withAlert') %}
			<div class="alert alert-success">
				<h4 class="alert-heading">Bravo !</h4>
				<p>
					Votre réservation auprés
					<strong>
						<a href="{{ path("user_show", {'slug':author.slug})}}">{{author.fullName}}</a>
					</strong>
					pour l'annonce
					<strong>
						<a href="{{ path("ads_show", {'slug':ad.slug})}}">{{ad.title}}</a>
					</strong>
					a bien été prise en compte !
				</p>
			</div>

		{% endif %}
		<div class="row">
			<div class="col">

				<div class="alert alert-light">
					<h2>Détails</h2>
					<dl class="row">
						<dt class="col-md-4">Numéro</dt>
						<dd class="col-md-8">{{booking.id}}</dd>
						<dt class="col-md-4">Date d'arrivée</dt>
						<dd class="col-md-8">
							{{booking.startDate | date('d/m/y')}}
						</dd>
						<dt class="col-md-4">Date de départ</dt>
						<dd class="col-md-8">{{booking.endDate | date('d/m/y')}}</dd>
						<dt class="col-md-4">Nombre de nuits</dt>
						<dd class="col-md-8">{{booking.duration}}</dd>
						<dt class="col-md-4">Montant total</dt>
						<dd class="col-md-8">{{booking.amount | number_format(2,',',' ')}}
							&euro;</dd>
						<dt class="col-md-4">Commentaire</dt>
						<dd class="col-md-8">{{booking.Comment | default('aucun commentaire')}}</dd>
					</dl>

					<hr>
					<h2 class="alert-heading">Votre hote</h2>
					<div class="row mb-3">
						<div class="clo-3">
							<img src="{{author.picture}}" alt="avatar de {author.fullName}}" class="avatar avatar-medium">


						</div>
						<div class="col-9">
							<h4>
								<a href="{{ path('user_show',{'slug':author.slug})}}">{{author.fullName}}</a>
							</h4>
							<span class="badge badge-primary">
								{{author.ads|length}}</span>
						</div>
					</div>
					{{author.descritption | raw }}
					<a href="{{path("user_show",{'slug':author.slug})}}" class="btn btn-primary">Plus d'info sur
						{{author.firstName}}</a>

				</div>
            <div class="alert alert-light" id="comment">
			<h2 class="alert-heading">votre avis compte !</h2>
			{% if date() > date(booking.endDate) %}
			{% set comment = booking.ad.commentFromAuthor(app.user) %}
			{% if comment is not null %}
              <blockquote>
			  {{comment.content}}
			  </blockquote>
			  <strong>Note :	</strong> {% include 'partials/rating.html.twig' with { 'rating': comment.rating } %}
			  {% else %}
				  
			{{ form_start(form) }}
			{{ form_widget(form) }}
             <button type="submit" class="btn success">Confirmer !</button>
			{{ form_end(form) }}

			{% endif %}
			
			
			{% else %}
			<p>Vous ne pourrez pas noter annonce tant que votre voyage ne sera pas complet ! </p>	
			
			
			
			{% endif %}
			
			
				</div>
           

			</div>
			<div class="col">
				<div class="alert alert-light">
					<h2 class="alert-heading">Votre hébergement</h2>
					<h4>
						<a href="{{ path('ads_show',{'slug':ad.slug}) }}">{{ad.title}}</a>

					</h4>
					<img src="{{ad.coverImage}}" alt="image de {{ad.title}}" class="img-fluid">
					{{ad.content | raw}}
					<a href="{{path('ads_show',{'slug':ad.slug})}}" class="btn btn-primary">Plus d'informations</a>
				</div>


			</div>
		</div>
	</div>

{% endblock %}